import "@/styles/globals.css";
import ThemeRegister from "@/components/ThemeRegister";
import MyLayout from "@/components/Layout";

import { Geist, Geist_Mono, Manrope } from "next/font/google";

import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Teamify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/setting.svg" />
      </Head>
      <ThemeRegister>
        <div
          className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable}`}
        >
          <MyLayout>
            <Component {...pageProps} />
          </MyLayout>
        </div>
      </ThemeRegister>
    </>
  );
}
