import { Box, Typography } from "@mui/material";
import Head from "next/head";
import React from "react";

export default function employees() {
  return (
    <>
      <Head>
        <title>Employees | Teamify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/setting.svg" />
      </Head>
      <Box mt={4}>
        <Typography variant="h5" fontWeight={700}>
          Employees
        </Typography>
      </Box>
    </>
  );
}
