import { getDashboardData } from "@/api";
import Dashboard from "@/components/Dashboard";
import Head from "next/head";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Dasboard | Teamify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/setting.svg" />
      </Head>
      <Dashboard data={data} />
    </>
  );
}

export async function getStaticProps() {
  const res = await getDashboardData();

  return { props: { data: res.data } };
}
