import { Box, Typography } from "@mui/material";
import Head from "next/head";

export default function projects() {
  return (
    <>
      <Head>
        <title>Projects | Teamify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/setting.svg" />
      </Head>
      <Box mt={4}>
        <Typography variant="h5" fontWeight={700}>
          Projects
        </Typography>
      </Box>
    </>
  );
}
