import { Box, Grid, Paper, Typography } from "@mui/material";
import Head from "next/head";
import { useRouter } from "next/router";
import { getDataTeams } from "@/api";

export default function teams({ teamsData }) {
  // const [teamsData, setTeamsData] = useState([]);
  // useEffect(() => {
  //   getDataTeams().then((res) => setTeamsData(res.data.teamsData));
  // }, []);
  if (!teamsData) return <div>Data yo'q</div>;
  const location = useRouter();
  return (
    <>
      <Head>
        <title>Teams | Teamify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/setting.svg" />
      </Head>
      <Box mt={4}>
        <Typography variant="h5" fontWeight={700}>
          Teams
        </Typography>
        <Grid container spacing={1.5} mt={2}>
          {teamsData?.map(({ id, name, count }, idx) => (
            <Grid size={{ xs: 12, sm: 6, md: 6, lg: 3 }} key={id}>
              <Box
                display={"flex"}
                justifyContent={"center"}
                onClick={() => location.push("/teams/" + id)}
                sx={{ cursor: "pointer" }}
              >
                <Paper sx={{ width: "100%", p: 2 }}>
                  <Typography variant="h5" fontWeight={"bold"}>
                    {name}
                  </Typography>
                  <Typography>{count} ishtirokchi</Typography>
                </Paper>
              </Box>
            </Grid>
          ))}
        </Grid>
      </Box>
    </>
  );
}

export async function getStaticProps() {
  try {
    const res = await getDataTeams();
    return { props: { teamsData: res.data.teamsData } };
  } catch (error) {
    return {
      props: {
        teamsData: null,
      },
    };
  }
}
